name: PRODUCTION CI/CD

on:
    # push:
    #     branches: [ "main" ]
    # pull_request:
    #     branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Check Out Repository
              uses: actions/checkout@v4

            - name: Set Environment Variables
              run: |
                  echo "${{ secrets.QINI_CMS_ENV }}" | tr -d '\r' > .env

            - name: Build Docker image
              env:
                  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  USER_NAME: root
                  IP: ${{ secrets.IP }}
                  PASSWORD: ${{ secrets.PASSWORD }}

              run: |
                  mkdir -p ~/.ssh
                  echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
                  chmod 700 ~/.ssh/id_rsa

                  touch ~/.ssh/config
                  chmod 600 ~/.ssh/config
                  echo "ServerAliveInterval 600" >> ~/.ssh/config

                  rsync -avzr --rsync-path="mkdir -p /apps/qini-cms && rsync" --delete -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' ./ $USER_NAME@$IP:/apps/qini-cms
                  ssh -o ServerAliveInterval=600 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER_NAME@$IP "cd /apps/qini-cms && docker compose up -d --build && docker system prune -f -a"
